### ISSUE TITLE
Can't install orjson in MacOS

### ISSUE THREAD

**Issue by francomor** [netlas-io/netlas-python#3]
When I tried to install netlas using pip3 I can't because orjson can't be installed quickly on MacOS. Any solution?

`
            ➜  ~ pip3 install netlas                                             
            Collecting netlas
              Using cached netlas-0.3.0-py3-none-any.whl (9.4 kB)
            Requirement already satisfied: appdirs>=1.4.3 in /usr/local/lib/python3.10/site-packages (from netlas) (1.4.4)
            Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.10/site-packages (from netlas) (6.0)
            Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.10/site-packages (from netlas) (4.64.1)
            Collecting orjson<=3.6.0,>=3.0.1
              Using cached orjson-3.6.0.tar.gz (746 kB)
              Installing build dependencies ... done
              Getting requirements to build wheel ... done
              Preparing metadata (pyproject.toml) ... error
              error: subprocess-exited-with-error
              
              × Preparing metadata (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [13 lines of output]
                  Error in sitecustomize; set PYTHONVERBOSE for traceback:
                  AssertionError:
                  💥 maturin failed
                    Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
                    Caused by: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information
                  
                  Caused by:
                    process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Z mutable-noalias=yes --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
                    --- stderr
                    error: the option `Z` is only accepted on the nightly compiler
                  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/.../pip-modern-metadata-xq0ijrmv', '--interpreter', '/usr/local/Cellar/python@3.10/3.10.8/bin/python3.10']' returned non-zero exit status 1.
                  Checking for Rust toolchain....
                  Running `maturin pep517 write-dist-info --metadata-directory /.../pip-modern-metadata-xq0ijrmv --interpreter /usr/local/Cellar/python@3.10/3.10.8/bin/python3.10`
                  [end of output]
              
              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: metadata-generation-failed
            
            × Encountered error while generating package metadata.
            ╰─> See above for output.
            
            note: This is an issue with the package mentioned above, not pip.
            hint: See above for details.
`

**Comment by netlas-io** [comment]
Can you check this issue in venv?
`python3 -m venv venv`
`source venv/bin/activate`
`pip3 install netlas`
